Candihub/pixel

Pipfile
Pipfile.lock
README.md
apps/core/admin.py
apps/core/models.py
apps/core/tests.py
apps/core/tests/test_views.py
manage.py
pixel/settings.py
pixel/wsgi.py
pytest.ini

Add tests for the core app

---

.circleci/config.yml
docs/circle-ci.md

Integrate CircleCI workflow

---

.circleci/config.yml
.flake8

Fix CircleCI integration

---

docs/circle-ci.md

Let me know if something is unclear in this documentation.

Add docs about Pipenv integration in CircleCI

---

.circleci/config.yml
Pipfile
Pipfile.lock
README.md
docs/circle-ci.md
docs/coveralls.md
setup.cfg

Add code coverage

---

.circleci/config.yml
docs/coveralls.md

Fix code coverage reporting

---

.circleci/config.yml
Makefile
README.md

Add makefile

---

README.md

Fix project name 😬

---

apps/data/tests.py
apps/data/tests/test_models.py

Add data models tests

---

Pipfile
Pipfile.lock
apps/data/factories.py
apps/data/tests/test_factories.py

Add data factories

---

apps/core/models.py
apps/core/tests/test_models.py

Add core models tests

---

apps/core/models.py
apps/core/tests/test_models.py
apps/data/models.py

Increase test coverage for core models

---

.circleci/config.yml
Makefile
README.md

Add CI front-end build

---

.circleci/config.yml
.dockerignore
Dockerfile
Makefile
Pipfile
Pipfile.lock
README.md
bin/ci
docker-compose.test.yml
docker-compose.yml
docker/usr/local/etc/gunicorn/pixel.py
docs/docker.md
env.d/development
env.d/test
pixel/settings.py
setup.cfg

Add docker environment

---

apps/core/factories.py

Fix warnings Pytest

---

.circleci/config.yml
Makefile
bin/ci
docker-compose.test.yml
docs/docker.md

Simplify CI workflow

---

.circleci/config.yml
bin/ci

Fix docker tag resolution

---

.circleci/config.yml
Makefile
README.md
docker-compose.yml

Dockerize the node stack

---

README.md

Add a note about requirements

---

.dockerignore
Makefile

This PR fixes the following issues:

Various fixes

---

Dockerfile
docker-compose.staging.yml
docker-compose.test.yml
docker-compose.yml
docker/etc/nginx/conf.d/pixel.conf
docker/usr/local/etc/gunicorn/pixel.py
pixel/settings.py

The following task will be postponed in a new PR:
- Create `bin/deploy` script (#14):
* Create `.env` file
* Copy nginx configuration
* Copy docker compose script
* Perform database migrations
* Restart docker compose

Deploy to staging

---

docs/data_modeling.md

Change documentation to generate model overview with docker

---

.circleci/config.yml

Static cache was not updated for the master branch if the yarn.lock file didn't
change.

Fix static cache

---

.circleci/config.yml

Add compiled styles build debug informations.

Add sha256 checksum to compiled styles

---

assets/scss/_layout.scss

This minor change helps me check the deployment process before freezing (and
documenting) it.

Add more padding to the footer

---

apps/submission/flows.py
apps/submission/io/archive.py
apps/submission/templates/submission/partials/step-tabs.html
apps/submission/templates/submission/submission/task_detail.html
apps/submission/templatetags/submission.py
apps/submission/tests/io/test_archive.py
apps/submission/tests/test_templatetags.py
apps/submission/tests/test_views.py
assets/scss/_submission.scss

Improve archive importation workflow

---

apps/submission/templates/submission/base.html
apps/submission/templates/submission/download_xlsx_template.html
apps/submission/templates/submission/submission/start.html
apps/submission/templates/submission/submission/task_detail.html
apps/submission/templates/submission/upload_archive.html
apps/submission/templates/submission/validation.html
apps/submission/templatetags/submission.py
apps/submission/tests/test_utils.py
apps/submission/tests/test_views.py
apps/submission/urls.py
apps/submission/utils.py
apps/submission/views.py

Improve flow navigation

---

apps/submission/templates/submission/base.html
apps/submission/templates/submission/download_xlsx_template.html
apps/submission/templates/submission/submission/task_detail.html
apps/submission/templates/submission/upload_archive.html
apps/submission/templates/submission/validation.html
apps/submission/templatetags/submission.py
apps/submission/tests/test_templatetags.py
assets/scss/main.scss

Add submission progress bar

---

apps/submission/templates/submission/submission/process_list.html
assets/scss/_submission.scss
assets/scss/main.scss

Improve process list

---

pixel/settings.py

Fix #110
---
This PR adds a new `ADMINS` and email settings.

Add SMTP configuration

---

apps/submission/models.py
apps/submission/templates/submission/submission/process_list.html
apps/submission/tests/test_models.py
apps/submission/tests/test_templatetags.py
assets/scss/_commons.scss
assets/scss/_submission.scss

Flag submission process errors

---

apps/submission/templates/submission/validation.html

Fix validation submission button label

---

setup.cfg
tests/test_registration.py

Add integration tests for the registration app

---

docs/release-process.md

Add documentation for the release process

---

apps/submission/templates/submission/submission/import_archive_detail.html
assets/scss/_commons.scss

This PR implements a wait page with a refresh button while waiting for the importation process to finish.

Add import wait page

---

docker-compose.production.yml
docker-compose.staging.yml

This PR addresses & fix issue #121 
Add `restart: always` to staging & production services

Add docker auto restart policy

---

README.md

Add microbadger badges

---

Makefile
README.md
docs/management_commands.md

Document and improve initial data loading

---

apps/core/admin.py
apps/core/models.py
apps/core/tests/test_admin.py

Various improvements to make Pixel's admin more user-friendly.

Improve admin

---

pixel/settings.py

update admins email address (settings)

---

Makefile
apps/core/factories.py
apps/core/management/commands/make_development_fixtures.py
apps/core/tests/__init__.py
apps/core/tests/test_admin.py
apps/core/tests/test_commands.py
apps/core/tests/test_factories.py
apps/submission/tests/io/test_archive.py
apps/submission/tests/io/test_pixel.py
apps/submission/tests/io/test_xlsx.py
apps/submission/tests/test_views.py
pixel/settings.py

We need a way to generate faked (but realistic) data sets used for development purpose.
This PR implements a new management command to create realistic pixel sets (and related objects):
```bash
$ python manage.py make_development_fixtures --pixel-sets=12
```

Add development fixtures generator

---

Pipfile
Pipfile.lock
apps/explorer/forms.py
apps/explorer/templates/explorer/pixelset_list.html
apps/explorer/tests/test_views.py
apps/explorer/views.py
assets/scss/_commons.scss
assets/scss/_explorer.scss
assets/scss/_layout.scss
assets/scss/_mixins.scss
assets/scss/main.scss
pixel/settings.py
templates/base.html
templates/foundation/pagination.html

Add filters to ease pixel set search.
* species
* omics unit types
* omics areas
* tags

Add pixelset list view filtering

---

apps/explorer/templates/explorer/pixelset_list.html
apps/explorer/tests/utils/test_export.py
apps/explorer/utils/__init__.py
apps/explorer/utils/export.py

Fix https://github.com/Candihub/pixel/issues/158

[WIP] Export the pixels

---

apps/explorer/templates/explorer/pixelset_list.html

Add clean filters button (pixel set list view)

---

apps/explorer/forms.py
apps/explorer/templates/explorer/pixelset_detail.html
apps/explorer/tests/test_forms.py
apps/explorer/tests/test_views.py
apps/explorer/views.py
assets/scss/_explorer.scss

Allow to preview pixels and export them

---

apps/explorer/templates/explorer/pixelset_detail.html
apps/explorer/tests/test_views.py

Add description to pixels preview

---

apps/explorer/forms.py
apps/explorer/templates/explorer/pixelset_list.html
apps/explorer/templatetags/explorer.py
apps/explorer/tests/test_templatetags.py
assets/scss/_explorer.scss

Add highlight template filter for pixelset list

---

apps/core/admin.py

Add omics units search by a ref. in the admin

---

apps/explorer/tests/test_views.py
apps/explorer/views.py

Fix descendant omics area filtering

---

apps/explorer/templates/explorer/pixelset_detail.html
apps/explorer/templates/explorer/pixelset_list.html
apps/explorer/tests/test_views.py
assets/scss/_explorer.scss
assets/scss/main.scss

Add completion (& release) dates to pixelset views

---

apps/core/management/commands/make_development_fixtures.py
apps/core/tests/test_commands.py

Fix #195
I had to add `no_color` to make the tests pass...

Do not use random for adding experiments to analyses

---

static/img/pixel-logo.svg

optimize svg

---

apps/submission/templates/submission/base.html
apps/submission/templates/submission/download_xlsx_template.html
assets/scss/_submission.scss

remove next links, add continue button in download step

---

apps/explorer/templates/explorer/pixelset_list.html

Add 'We can scroll horizontally with Shift + scroll' message

---

templates/base.html

Add titles to menu entries

---

apps/explorer/tests/test_views.py

Hopefully fix the random test failures

---

assets/scss/_explorer.scss
assets/scss/_home.scss

Fix CSS for tags in pixel sets list

---

apps/explorer/templates/explorer/pixelset_detail.html
apps/explorer/tests/test_views.py

Add links and refine edit links.

Pixel set/Pixel pages

---

apps/submission/templates/submission/submission/process_detail.html
apps/submission/templates/submission/submission/process_list.html
assets/scss/_submission.scss

Fix #167 
Fix #168
Fix #182
---

Add icon titles and remove actions in process list

---

apps/submission/templates/submission/submission/process_detail.html
apps/submission/templates/submission/submission/upload_detail.html
apps/submission/templates/submission/tags.html

Improve submission UX

---

apps/submission/io/pixel.py
apps/submission/tests/test_views.py

Improve error message when entries are missing

---

assets/scss/_submission.scss

Clean submission styles

---

apps/data/io/parsers.py
apps/data/tests/io/test_parsers.py

Add feature gene name to entry.description while importing database entries

---

apps/explorer/templates/explorer/pixelset_detail.html
apps/explorer/tests/test_views.py
apps/explorer/views.py

Move omics_units in session to a namespaced location

---

apps/explorer/forms.py
apps/explorer/templates/explorer/pixelset_list.html
apps/explorer/tests/test_views.py
apps/explorer/urls.py
apps/explorer/views.py
assets/scss/_explorer.scss

Add pixel set selection cart

---

bin/load-all-entries

Add script to load entries

---

apps/explorer/forms.py
apps/explorer/templates/explorer/pixelset_detail.html
apps/explorer/templates/explorer/pixelset_list.html
apps/explorer/tests/test_views.py
apps/explorer/urls.py
apps/explorer/views.py
assets/scss/_explorer.scss
templates/base.html

Add PixelSetUnselectView

---

apps/core/templates/core/home-authenticated.html
apps/core/tests/test_views.py
apps/core/views.py

Add an example of a pie chart on homepage

---

apps/explorer/templates/explorer/_help_table.html
apps/explorer/templates/explorer/_subset_selection.html
apps/explorer/templates/explorer/pixelset_detail.html
apps/explorer/templates/explorer/pixelset_list.html
apps/explorer/templates/explorer/pixelset_selection.html
apps/explorer/tests/utils/test_html.py
apps/explorer/utils/__init__.py
apps/explorer/utils/html.py
apps/explorer/views/views_selection.py
apps/submission/forms.py
assets/scss/_explorer.scss
assets/scss/_explorer_selection.scss

Refs #229 
---
I am a little concerned by the perf impact of such a change (i.e. not listing pixels but the dataframe used for the "pixel sets export") but let's see. It works correctly locally, and we will see with larger/real data.

Explore the selected pixel sets / Part 3

---

apps/explorer/templates/explorer/_pixelset_detail_pixels.html
apps/explorer/tests/utils/test_html.py
apps/explorer/utils/html.py

Better HTML generation of the selected pixel sets data

---

apps/core/management/commands/make_development_fixtures.py
apps/core/tests/test_commands.py

Fix make dev fixtures command

---

apps/explorer/templates/explorer/_subset_selection.html
apps/explorer/templates/explorer/pixelset_detail.html
apps/explorer/templates/explorer/pixelset_list.html
apps/explorer/templates/explorer/pixelset_selection.html
apps/explorer/tests/utils/test_export.py
apps/explorer/tests/views/test_views.py
apps/explorer/utils/export.py
apps/explorer/utils/html.py
apps/explorer/views/mixins.py
apps/explorer/views/views_list.py
apps/explorer/views/views_selection.py

Export selected pixel sets

---

apps/explorer/tests/utils/test_export.py
apps/explorer/utils/export.py
assets/scss/_explorer.scss
assets/scss/_explorer_list.scss

Add highlight on search terms (subset selection)

---

apps/explorer/forms.py
apps/explorer/templates/explorer/_pixelset_detail_pixels.html
apps/explorer/templatetags/explorer.py
apps/explorer/tests/test_templatetags.py
apps/explorer/tests/views/test_views_selection.py
apps/explorer/utils/export.py
apps/explorer/views/views_detail.py

Highlight matched search terms everywhere

---

apps/explorer/forms.py
apps/explorer/tests/views/test_views_list.py
apps/explorer/views/views_list.py

Search pixel sets by analysis

---

apps/explorer/templates/explorer/_subset_selection.html
apps/explorer/tests/views/test_views_detail.py
apps/explorer/tests/views/test_views_selection.py
apps/explorer/urls.py
apps/explorer/views/__init__.py
apps/explorer/views/views_detail.py
apps/explorer/views/views_list.py
apps/explorer/views/views_selection.py
assets/scss/_explorer.scss

Add a "clear" button for the subset selection

---

apps/core/templates/core/home-authenticated.html
apps/core/views.py
assets/scss/_home.scss
assets/scss/main.scss

Omicsarea tree in homepage

---

apps/core/templates/core/home-authenticated.html
assets/scss/_home.scss

Fix conflict between Google chart and foundation styles

---

apps/core/templates/core/home-authenticated.html
apps/core/views.py

Add new chart : Pixel by Omics unit type

---

apps/core/templates/core/home-authenticated.html
apps/core/views.py

Add new chart : pixels by omics area

---

apps/core/templates/core/home-authenticated.html
apps/core/views.py

Add new chart tags infos

---

apps/core/templates/core/home-authenticated.html
apps/core/views.py
assets/scss/_home.scss

Add new table : Pixeler infos

---

apps/core/templates/core/home-authenticated.html
apps/core/views.py

Add new chart : analysis saved at

---

apps/core/templates/core/home-authenticated.html
apps/core/views.py
assets/scss/_home.scss

Add number of Pixels

---

apps/core/templates/core/home-authenticated.html
apps/core/views.py
assets/scss/_home.scss
assets/scss/_settings.scss

Grid organisation of Dashboard

---

apps/core/templates/core/home-authenticated.html
assets/scss/_home.scss

Add style in dashboard

---

apps/core/templates/core/home-authenticated.html
apps/core/views.py

Add new counters in dashboard 

---

.zenodo.json
docs/release-process.md

Add a specic config file for Zenodo with authors' name and ORCID.
Fix #289

Prepare files for automatics archiving into Zenodo
